 source "git@gitlab.alibaba-inc.com:alipods/specs.git"
 source "git@gitlab.alibaba-inc.com:alipods/specs-mirror.git"

 platform :ios, '7.0'
#inhibit_all_warnings!

def common
    pod 'SocketRocket', '0.4.2'
    
end

target 'LHFDemo' do
    common
end

target 'LHFDemoTests' do
    common
end
